# Generated by Django 4.2.7 on 2024-05-07 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='symptom',
        ),
    ]
